language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '10.22.0'
  - '14.15.1'
after_success:
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
